name: Deploy to Firebase

on:
  push:
    paths:
      - 'functions/src/**'
      - 'functions/package.json'
      - 'functions/webpack.config.js'
      - 'ui/src/**'
      - 'ui/package.json'
      - 'ui/webpack.config.js'
    branches:
      - master

jobs:
  build_and_deploy:
    name: Lint and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node 8
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install dependencies
        run: yarn
      - name: Run tslint in the functions folder
        run: yarn --cwd functions run lint
      - name: Deploy to Firebase
        run: yarn deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
